language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: EUAAHpixd1tuVbNk7jrFQ6Dq5tfXrZlIcS6nwFD6Lnt2kbbCMVwfRY/xHGvzn6a2W6yhy1E5inXhye5u4GUDz/9QU0C81xpYbcUqMq3+tS+fAl7xsTxdj37kqtex8WTVlXIxLIdk9ed4jZGSPWg7kj7F4n2YTh+m5ix3OjS3cYpv0eOnFjem58iASpBRUkF/RRykuwpYkl7DSHqWt1/QWOWP5Yu5EUXrJKHkFXsUziDcTXGqy6AsRwDakUjwPGtG/xhcDyIuFjdQRIt4NBElT58AcB0GCoY+5YY8vaStxVO2kIL2bM5XmYguage6SJWHV7RiscC+qD3zQNrLIlv86bXBnMsrAIL7F1d4MnoliODVx/Rdm8zi1vPEYk3EKlkprHc4iw0DLHYYpeJtkbbeZ3aH9H7e08HyBd4CVCsDN3zdcix1RgqO97lezL1iqS6NWFho0FN+qCJnijL98bDWB66x2bQwvfcsu5kqWjHT0iIcenfFRBE4YUC69gUX+QZHj+/Qt3/gYvGvvYLcs7ju9O1uYrcG7OSOF83kxLxUOE5oPDgoCP1fo6hwBUPc7DHMapaV5dvNJWzNcLuMosTGkM+tKzAJpy73z5EvuHp+yrpbM4vAp/sHzTBIyisDWBbnjB7COUv2XNmhHE7q1dzTxX5TFS1Z2UT5xOoVDDGngp0=
  app: infinite-hollows-38049
  on:
    repo: mrmojica/travis-test
